### ISSUE TITLE
Uncloak fails when using extras/cloak/ciphers/starTrek

### ISSUE THREAD

**Issue by 68420948** [dyne/tomb#522]
The cipher extras/cloak/ciphers/starTrek contains trailing whitespace (tabstops) causing 'tomb uncloak ...' to fail like this:

```
~~ Cloak a key file ...
+ echo ~~ Cloak a key file ...
+ /usr/bin/tomb cloak -k argon2-test.key extras/cloak/ciphers/starTrek cloaked_key.txt
tomb  .  Key is valid.
tomb (*) Encoding key argon2-test.key using cipher extras/cloak/ciphers/starTrek
tomb (*) Tomb key encoded succesfully
~~ Uncloak and verify a key file ...
+ echo ~~ Uncloak and verify a key file ...
+ /usr/bin/tomb uncloak cloaked_key.txt extras/cloak/ciphers/starTrek uncloaked.key
Traceback (most recent call last):
  File "/usr/libexec/tomb/decloakify", line 84, in <module>
    Decloakify(args.input, args.cipher, args.output, args.password)
  File "/usr/libexec/tomb/decloakify", line 66, in Decloakify
    clear64 +=  array64[arrayCipher.index(line)]
                        ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'Daniels\n' is not in list
tomb [W] Nothing found in cloaked_key.txt

```

**Comment by jaromil** [comment]
fixed in [8d3d6ec](https://github.com/dyne/tomb/commit/8d3d6ecda4d8ad82a356d9d72f0341e985fd5c21)
